3.0.5

CREATING A DATA FRAME FROM A DICTIONARY

In [7]:
# Create a dictionary containing student information
students_dictionary = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["John", "Mary", "Peter", "Asha", "David"],
    "Age": [20, 21, 19, 22, 20]
}

# Convert the dictionary into a DataFrame
students_dict_df = pd.DataFrame(students_dictionary)

# Display the DataFrame
students_dict_df

   ID   Name  Age
0   1   John   20
1   2   Mary   21
2   3  Peter   19
3   4   Asha   22
4   5  David   20

display the columns:

In [8]:
students_dict_df.columns

Index(['ID', 'Name', 'Age'], dtype='str')

Display the data types:

In [9]:
students_dict_df.dtypes

ID      int64
Name      str
Age     int64
dtype: object

DataFrame from Series

In [11]:
# Create three Pandas Series
student_names = pd.Series(["John", "Mary", "Peter", "Asha", "David"])
student_ages = pd.Series([20, 21, 19, 22, 20])
student_scores = pd.Series([75, 82, 68, 91, 79])

# Combine the Series into a DataFrame
students_series_df = pd.DataFrame({
    "Name": student_names,
    "Age": student_ages,
    "Score": student_scores
})

# Display the DataFrame
print(students_series_df)

    Name  Age  Score
0   John   20     75
1   Mary   21     82
2  Peter   19     68
3   Asha   22     91
4  David   20     79

PART B — GROUP 7: HEART DISEASE DATASET

1. IMPORTING THE DATA
Load the CSV

In [12]:
# Load the Heart Disease dataset
heart_df = pd.read_csv("heart.csv")

# Display the first 10 records
heart_df.head(10)

,sex,age,cp,resting_BP,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Max Heart Rate Reserve,Heart Disease Risk Score,target
0,male,65,0,130,254,0,0,147,0,1.4,1,1,3,10,11.44,0
1,male,53,0,140,261,0,0,186,1,0.0,2,0,2,-17,13.51,1
2,male,50,0,122,222,0,0,186,0,0.0,2,0,2,-14,9.46,1
3,female,47,1,112,160,0,1,138,0,0.0,1,0,2,37,8.34,1
4,male,47,0,142,309,0,0,147,1,0.0,1,3,3,28,13.43,0
5,female,64,0,124,209,0,1,163,0,0.0,2,0,2,-5,10.77,1
6,female,65,1,140,195,0,1,179,0,0.0,2,2,2,-22,11.05,1
7,male,42,0,152,223,0,1,181,0,0.0,2,0,3,-1,9.27,0
8,female,57,0,180,327,0,2,117,1,3.4,1,0,2,48,15.37,0
9,male,70,2,180,274,1,0,150,1,1.6,1,0,3,2,18.14,0

Check the shape

In [14]:
heart_df.shape

(1035, 16)

2. STATISTICS

In [18]:
heart_df.describe

<bound method NDFrame.describe of          sex  age  cp  resting_BP  chol  fbs  restecg  thalach   exang  \
0       male   65   0         130   254    0        0       147      0
1       male   53   0         140   261    0        0       186      1
2       male   50   0         122   222    0        0       186      0
3     female   47   1         112   160    0        1       138      0
4       male   47   0         142   309    0        0       147      1
...      ...  ...  ..         ...   ...  ...      ...       ...    ...
1030  female   45   2         145   195    0        1       180      1
1031    male   53   0         125   210    0        1       165      0
1032  female   60   1         130   240    1        0       150      1
1033    male   67   2         155   205    0        1       140      0
1034  female   59   0         110   175    0        1       172      1

      oldpeak  slope  ca  thal  Max Heart Rate Reserve  \
0         1.4      1   1     3                      10
1         0.0      2   0     2                     -17
2         0.0      2   0     2                     -14
3         0.0      1   0     2                      37
4         0.0      1   3     3                      28
...       ...    ...  ..   ...                     ...
1030      3.0      1   0     2                      -5
1031      0.8      1   1     3                       2
1032      2.2      2   2     1                      10
1033      1.1      0   0     2                      13
1034      2.5      1   3     2                     -11

      Heart Disease Risk Score  target
0                        11.44       0
1                        13.51       1
2                         9.46       1
3                         8.34       1
4                        13.43       0
...                        ...     ...
1030                     15.90       1
1031                     13.20       0
1032                     18.80       1
1033                     16.10       0
1034                     12.90       1

[1035 rows x 16 columns]>